name: Build pifire variants to test install

on:
  push:
    branches:
      - develop
      - install-script
  workflow_dispatch:

jobs:
  test-install:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        os: [bullseye, bookworm, trixie]
        target: [base, uv, venv, dev]
        variant: [32, 64]

        exclude:
          - variant: 32
            os: trixie
          - variant: 32
            target: uv
          - variant: 64
            os: bullseye
          - variant: 64
            target: venv

        include:
          # Map target to flag
          - target: base
            flag: ""
          - target: uv
            flag: -uv
          - target: venv
            flag: -venv
          - target: dev
            flag: -dev
          # Map variant to platforms (for runtime emulation)
          - variant: 32
            platforms: linux/arm/v7
          - variant: 64
            platforms: linux/arm64

      fail-fast: false
      max-parallel: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: docker-layers-${{ runner.os }}-${{ matrix.platforms }}-${{ matrix.os }}-${{ hashFiles('auto-install/Dockerfile') }}
          restore-keys: |
            docker-layers-${{ runner.os }}-${{ matrix.platforms }}-${{ matrix.os }}-

      - name: Build Raspbian image – ${{ matrix.variant }}bit ${{ matrix.os }}
        uses: docker/build-push-action@v5
        with:
          context: auto-install
          load: true
          push: false
          platforms: ${{ matrix.platforms }}
          build-args: |
            OS=${{ matrix.os }}
            TARGETVARIANT=${{ matrix.variant }}
            TARGETPLATFORM=${{ matrix.platforms }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          tags: raspbian:${{ matrix.target }}-${{ matrix.os }}-${{ matrix.variant }}bit

      # Temp fix for https://github.com/docker/build-push-action/issues/252
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Test install.sh ${{ matrix.target }} on ${{ matrix.variant }}bit ${{ matrix.os }}
        run: |
          echo "# Testing Install: ${{ matrix.variant }}bit ${{ matrix.os }} - ${{ matrix.target }}" >> $GITHUB_STEP_SUMMARY
          echo "<details><summary>Click to expand build log</summary>" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          docker run --rm \
              --platform ${{ matrix.platforms }} \
              raspbian:${{ matrix.target }}-${{ matrix.os }}-${{ matrix.variant }}bit \
              /bin/bash -c "bash -x /home/pi/install.sh $INSTALL_FLAG" \
              2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

          echo "build_status=SUCCESS" >> $GITHUB_OUTPUT

      - name: Report great success
        if: steps.build.outcomes.build_status == 'SUCCESS'
        run: |
          echo "SUCCESS | ${{ matrix.variant }}bit | ${{ matrix.os }} | ${{ matrix.target }}" >> $GITHUB_STEP_SUMMARY

      - name: Report abject failure
        if: failure()
        run: |
          echo "FAILED | ${{ matrix.variant }}bit | ${{ matrix.os }} | ${{ matrix.target }}" >> $GITHUB_STEP_SUMMARY

